Coding branch
phalado/Enumerable-Methods pull request #1
Opened 2019-11-19 22:57 UTC by phalado

Sorry for the requests TSEs, now I think it's alright.

2019-11-20 22:37 UTC, stratospherique requested changes
### Good start @phalado :clap: :clap: However, some requirements needs to be implemented in order for us to approve your project. check below :arrow_down: 

- **[REQUIRED]** Check the code comments below, use the notes to refactor you methods :nerd_face: 

- **[REQUIRED]** Remove all debugging code (e.g commented code, etc...)

### That's it :relaxed: When finished, kindly resubmit another code review request :pray: 

Happy coding :v: 
**_Ahmed Mahfoudh_**

2019-11-20 22:37 UTC, stratospherique commented on enumerable.rb
> +  end
* [ ] If no block is given (i.e check with block_given? at the beginning of the method) the method should return an Enumerator.

2019-11-20 22:37 UTC, stratospherique commented on enumerable.rb
> +  end
* [ ] If no block is given (i.e check with block_given? at the beginning of the method) the method should return an Enumerator.
* [ ] my_each_with_index calls the given block once for each element in self
  - the first argument of my_each should be the item and second argument should be the index. You are doing the opposite.

2019-11-20 22:37 UTC, stratospherique commented on enumerable.rb
> +  end
* [ ] If no block is given (i.e check with block_given? at the beginning of the method) the method should return an Enumerator.

2019-11-20 22:37 UTC, stratospherique commented on enumerable.rb
> +  end
* [ ] If no block is given (i.e check with block_given? at the beginning of the method) the method should return an Enumerator.
* [ ] the method should be able to take classes, regex exp, primitive types values as arguments, yours raise an error when do so :red_circle: 

example:
```ruby
    array = [1,2,5,4,7]
    p array.my_all?(Integer)
    # return this error
    #ArgumentError:
    #   wrong number of arguments (given 1, expected 0)
     # ./enumerable.rb:28:in `my_all?'

  ```

2019-11-20 22:37 UTC, stratospherique commented on enumerable.rb
> +  end
* [ ] If no block is given (i.e check with block_given? at the beginning of the method) the method should return an Enumerator.
* [ ] the method should be able to take classes, regex exp, primitive types values as arguments, yours raise an error when do so :red_circle: 

example:
```ruby
    array = [1,2,5,4,7]
    p array.my_any?(Integer)
    # return this error
    #ArgumentError:
    #   wrong number of arguments (given 1, expected 0)
     # ./enumerable.rb:36:in `my_any?'

  ```

2019-11-20 22:37 UTC, stratospherique commented on enumerable.rb
> +  end
* [ ] If no block is given (i.e check with block_given? at the beginning of the method) the method should return an Enumerator.
* [ ] the method should be able to take classes, regex exp, primitive types values as arguments, yours raise an error when do so :red_circle: 

example:
```ruby
    array = [1,2,5,4,7]
    p array.my_none?(Integer)
    # return this error
    #ArgumentError:
    #   wrong number of arguments (given 1, expected 0)
     # ./enumerable.rb:44:in `my_none?'

  ```

2019-11-20 22:37 UTC, stratospherique commented on enumerable.rb
> +  end
* [ ] If no block is given (i.e check with block_given? at the beginning of the method) the method should return an Enumerator.
* [ ] the method should be able to take literals as arguments, yours raise an error when do so :red_circle: 

example:
```ruby
    array = [1,2,5,4,7]
    p array.my_count # should print the number of items
    # return this error
    #ArgumentError:
    #   wrong number of arguments (given 1, expected 0)
     # ./enumerable.rb:52:in `my_count'

  ```

2019-11-20 22:37 UTC, stratospherique commented on enumerable.rb
> +  end
* [ ] the method should return an Enumerator in the example below
example:
```ruby
    array = [1,2,5,4,7]
    p array.my_map
    # return this error
    # NoMethodError:
      #  undefined method `call' for nil:NilClass
      # ./enumerable.rb:68:in `block in my_map'
      # ./enumerable.rb:7:in `my_each'
      # ./enumerable.rb:67:in `my_map'
  ```

2019-11-20 22:37 UTC, stratospherique commented on enumerable.rb
> +end
* [ ] the method should be able to take literals, to_proc symbols(e.g :+, :-, etc... ) as arguments, yours raise an error when doing so red_circle

```ruby
range = Range.new(5,50)
range.my_inject(4) { |prod, n| prod * n }
      # return this error
      # ArgumentError:
      #  wrong number of arguments (given 1, expected 0)
      # ./enumerable.rb:74:in `my_inject'
```

2019-11-21 02:45 UTC, whiz25 requested changes
## Good job @phalado :+1: 
I see you implemented previously suggested requirements. That's good.
However, we can't merge this one yet because some edge cases are still failing. See my comments and please do your best to implement the suggestions to the best of your ability.

### Martin Afani

2019-11-21 02:46 UTC, whiz25 commented on enumerable.rb
> +  end
- [ ] when a class is passed as an argument returns true if all of the collection is a member of such class
- [ ]  when a Regex is passed as an argument returns true if all of the collection matches the Regex
- [ ] when a pattern other than Regex or a Class is given returns true if all of the collection matches the pattern

2019-11-21 02:47 UTC, whiz25 commented on enumerable.rb
> +  end
- [ ] when no block or argument is given returns true if at least one of the collection is not false or nil
- [ ] when a class is passed as an argument returns true if at least one of the collection is a member of such class
- [ ] when a Regex is passed as an argument returns false if none of the collection matches the Regex
- [ ] hen a pattern other than Regex or a Class is given returns false if none of the collection matches the pattern

2019-11-21 02:48 UTC, whiz25 commented on enumerable.rb
> +  end
- [ ] when a pattern other than Regex or a Class is given returns true only if none of the collection matches the pattern

2019-11-21 02:48 UTC, whiz25 commented on enumerable.rb
> +  end
- [ ] combines all elements of enum by applying a binary operation, specified by a block
- [ ] when a symbol is specified combines each element of the collection by applying the symbol as a named method

2019-11-21 17:20 UTC, uche-inyama requested changes
Hi Phalado!

Your methods are still failing the tests pointed out by my colleague, whiz25. 

I would suggest you go through this [document](https://ruby-doc.org/core-2.6.5/Enumerable.html). Use the test-cases in this doc, for similar methods, to test the methods you have written. Once the methods you have written pass the tests you should be fine.

When you are done submit another form for a code review.

#### ``` Have a great day ``` :slightly_smiling_face: 

``` Uchechukwu Henry Inyama ```

2019-11-21 22:37 UTC, phalado commented
> Hi Phalado!
> 
> Your methods are still failing the tests pointed out by my colleague, whiz25.
> 
> I would suggest you go through this [document](https://ruby-doc.org/core-2.6.5/Enumerable.html). Use the test-cases in this doc, for similar methods, to test the methods you have written. Once the methods you have written pass the tests you should be fine.
> 
> When you are done submit another form for a code review.
> 
> #### `Have a great day` 🙂
> `Uchechukwu Henry Inyama`

2019-11-21 22:41 UTC, phalado commented
> Hi Phalado!
> 
> Your methods are still failing the tests pointed out by my colleague, whiz25.
> 
> I would suggest you go through this [document](https://ruby-doc.org/core-2.6.5/Enumerable.html). Use the test-cases in this doc, for similar methods, to test the methods you have written. Once the methods you have written pass the tests you should be fine.
> 
> When you are done submit another form for a code review.
> 
> #### `Have a great day` 🙂
> `Uchechukwu Henry Inyama`

What tests are failing? All the tests that my partner and I have done are succeeding.

2019-11-22 09:56 UTC, uche-inyama commented
Hi Phalado!

You can reach me slack for clarifications. @ Inyama, Uchechukwu Henry

2019-11-22 18:52 UTC, wathigo approved these changes
# Approved :smile: 

Hi Devs,
Great work implementing the suggested changes :clap: 

### You may move on :next_track_button: 

_Good luck in your future projects :crossed_fingers: 
Reviewed by: **Simon Wathigo**_

2019-11-22 18:54 UTC, merged